// <auto-generated />
using System;
using Clippy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Clippy.Migrations
{
    [DbContext(typeof(ClippyContext))]
    [Migration("20210225193500_AddResources")]
    partial class AddResources
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("Clippy.Entities.Resource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("Location")
                        .IsUnique();

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2021, 2, 25, 19, 34, 59, 659, DateTimeKind.Utc).AddTicks(1850),
                            Location = "https://www.nationalgeographic.com",
                            Metadata = "{\"Title\":\"National Geographic\",\"MediaType\":\"text/html\"}"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2021, 2, 25, 19, 34, 59, 659, DateTimeKind.Utc).AddTicks(1850),
                            Location = "https://www.nps.gov/yell/index.htm",
                            Metadata = "{\"Title\":\"Yellowstone National Park\",\"MediaType\":\"text/html\"}"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2021, 2, 25, 19, 34, 59, 659, DateTimeKind.Utc).AddTicks(1850),
                            Location = "https://www.foodnetwork.com",
                            Metadata = "{\"Title\":\"Food Network\",\"MediaType\":\"text/html\"}"
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2021, 2, 25, 19, 34, 59, 659, DateTimeKind.Utc).AddTicks(1850),
                            Location = "https://www.loveandlemons.com",
                            Metadata = "{\"Title\":\"Love and Lemons\",\"MediaType\":\"text/html\"}"
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2021, 2, 25, 19, 34, 59, 659, DateTimeKind.Utc).AddTicks(1850),
                            Location = "https://appalachiantrail.org",
                            Metadata = "{\"Title\":\"Appalachian Trail Conservancy\",\"MediaType\":\"text/html\"}"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
